<a href="https://colab.research.google.com/github/DIPANJAN001/Andrew-Ng-Machine-Learning-Notes/blob/master/Thirthajit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score

# Generate synthetic data
n_samples = 100000
speed = np.random.normal(loc=60, scale=10, size=n_samples)
acceleration = np.random.normal(loc=0, scale=2, size=n_samples)
distance_to_obstacle = np.random.uniform(low=10, high=50, size=n_samples)
other_vehicle_speed = np.random.normal(loc=60, scale=10, size=n_samples)
other_vehicle_distance = np.random.uniform(low=10, high=50, size=n_samples)
collision = np.where((distance_to_obstacle - other_vehicle_distance) < 5, 1, 0)

# Split data into training and test sets
X_train = pd.DataFrame({'speed': speed[:80000],
                        'acceleration': acceleration[:80000],
                        'distance_to_obstacle': distance_to_obstacle[:80000],
                        'other_vehicle_speed': other_vehicle_speed[:80000],
                        'other_vehicle_distance': other_vehicle_distance[:80000]})
y_train = pd.Series(collision[:80000])
X_test = pd.DataFrame({'speed': speed[80000:],
                       'acceleration': acceleration[80000:],
                       'distance_to_obstacle': distance_to_obstacle[80000:],
                       'other_vehicle_speed': other_vehicle_speed[80000:],
                       'other_vehicle_distance': other_vehicle_distance[80000:]})
y_test = pd.Series(collision[80000:])

# Train logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Evaluate model performance
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)

Accuracy: 0.99995
Precision: 0.9999193418293273
Recall: 1.0

In [ ]:
X_train

,speed,acceleration,distance_to_obstacle,other_vehicle_speed,other_vehicle_distance
0,67.429382,-2.086369,41.764679,64.575632,30.407516
1,51.786333,0.870639,17.589025,59.912437,37.847475
2,57.517458,-2.701646,11.525177,77.304713,39.055699
3,60.524113,1.056804,39.236449,53.807154,34.595241
4,59.002150,-0.044611,23.096334,62.801132,48.693862
...,...,...,...,...,...
79995,49.624555,0.932159,37.236638,77.479356,14.216956
79996,62.319457,1.443398,32.305196,38.637390,13.709179
79997,54.791276,-2.637869,29.745090,27.626513,29.192945
79998,59.943038,1.572917,25.131745,59.212489,29.526049
79999,62.653038,1.779284,49.665672,53.256966,44.951109

In [ ]:
y_train

0        0
1        1
2        1
3        1
4        1
        ..
79995    0
79996    0
79997    1
79998    1
79999    1
Length: 80000, dtype: int64

In [ ]:
X_test

,speed,acceleration,distance_to_obstacle,other_vehicle_speed,other_vehicle_distance
0,48.288493,2.577711,21.807414,56.262860,39.829137
1,65.654463,1.294152,23.938859,63.232978,45.149888
2,68.566549,2.206776,43.446446,86.982508,15.448887
3,68.520132,-3.943434,24.266855,77.692103,10.469728
4,55.600811,1.073193,28.175719,52.914273,27.645710
...,...,...,...,...,...
19995,59.967705,0.322953,36.816828,68.145202,49.376683
19996,54.724288,3.214734,39.306396,32.909598,27.235406
19997,69.526770,0.952874,24.370277,54.463368,21.682647
19998,69.201001,0.393323,30.791975,42.733975,19.752778
19999,66.694152,0.046879,19.318394,64.371967,11.544521

In [ ]:
y_pred

array([1, 1, 0, ..., 1, 0, 0])